### ISSUE TITLE
Problems installing PLIM

### ISSUE THREAD

**Issue by mfm2174** [TiagoOlivoto/tiagoolivoto#1] opened 2023-11-26 21:16 UTC
I tried to download the package plin in CRAN and install it in R (LINUX MINT) but unfortunately I received the following message:

configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status
ERROR: dependency ‘units’ is not available for package ‘sf’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘units’ are not available for package ‘stars’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/stars’
Warning in install.packages :
  installation of package ‘stars’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘stars’, ‘terra’ are not available for package ‘pliman’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/pliman’
Warning in install.packages :
  installation of package ‘pliman’ had non-zero exit status
 
Can you help me please?

**Comment by TiagoOlivoto** [comment] 2023-11-26 21:23
> I tried to download the package plin in CRAN and install it in R (LINUX MINT) but unfortunately I received the following message:
> 
> configure: error: gdal-config not found or not executable.
> ERROR: configuration failed for package ‘terra’
> * removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/terra’
> Warning in install.packages :
>   installation of package ‘terra’ had non-zero exit status
> ERROR: dependency ‘units’ is not available for package ‘sf’
> * removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/sf’
> Warning in install.packages :
>   installation of package ‘sf’ had non-zero exit status
> ERROR: dependencies ‘sf’, ‘units’ are not available for package ‘stars’
> * removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/stars’
> Warning in install.packages :
>   installation of package ‘stars’ had non-zero exit status
> ERROR: dependencies ‘sf’, ‘stars’, ‘terra’ are not available for package ‘pliman’
> * removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/pliman’
> Warning in install.packages :
>   installation of package ‘pliman’ had non-zero exit status
>  
> Can you help me please?

You probably will need update the package list. There seems to be an issue with 'units'. Try reload the R section, update the package list and install pliman again

**Comment by mfm2174** [comment] 2023-11-26 21:50
I didn't understand with Reload the R section...do you mean to close R and restart it?

**Comment by TiagoOlivoto** [comment] 2023-11-26 21:52
Yes. If you're using Rstudio, you can use Ctrl + Shift + F10 too

**Comment by mfm2174** [comment] 2023-11-26 22:03
That is the message that I received after restarting R:  

configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status
ERROR: dependency ‘units’ is not available for package ‘sf’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘units’ are not available for package ‘stars’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/stars’
Warning in install.packages :
  installation of package ‘stars’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘stars’, ‘terra’ are not available for package ‘pliman’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/pliman’
Warning in install.packages :
  installation of package ‘pliman’ had non-zero exit status

It didn't work! Do you some other alternative?

**Comment by TiagoOlivoto** [comment] 2023-11-26 22:12
Try first install 'terra' from CRAN

**Comment by mfm2174** [comment] 2023-11-26 22:16
* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc
configure: CXX: g++ -std=gnu++14
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/home/mfm2174/R/x86_64-pc-linux-gnu-library/4.1/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status

It's not working either! Honestly, I do not know why is this happening. The same was happening in windows.

**Comment by TiagoOlivoto** [comment] 2023-11-26 22:21
So, the issue is not with pliman... I'm not a Linux user, so I can't point what's happening. Try to ask in some Linux forum . 
Best

**Comment by mfm2174** [comment] 2023-11-26 22:24
Thx anyway!

**Comment by TiagoOlivoto** [comment] 2023-11-27 11:06
Since this seems to be not related to pliman, I'm closing this now.
Feel free to reopen it if necessary

**Closed as completed by TiagoOlivoto** 2023-11-27 11:06 UTC
